test_camouflage : test_camouflage.cpp ../Camouflage.o ../Bestiole.o ../BestioleFactory.o ../gregaire.o ../peureuse.o ../kamikaze.o ../prevoyante.o ../PersonnaliteMultiple.o ../Carapace.o ../Nageoires.o ../Yeux.o ../Oreilles.o ../Milieu.o
	g++ -Wall -std=c++11 -o test_camouflage test_camouflage.cpp ../Camouflage.o ../Bestiole.o ../BestioleFactory.o ../gregaire.o ../peureuse.o ../kamikaze.o ../prevoyante.o ../PersonnaliteMultiple.o ../Carapace.o ../Nageoires.o ../Yeux.o ../Oreilles.o ../Milieu.o -I.. -lX11 -lpthread

clean:
	rm -f test_camouflage